name: Release APK/AAB

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.11'
          channel: stable

      - name: Get dependencies
        run: flutter packages get

      - name: Build APK
        run: flutter build apk --release # ou "flutter build appbundle --release" pour un AAB

      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Archive AAB
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master

      - name: Download APK/AAB
        uses: actions/download-artifact@v2
        with:
          name: app-release # nom de l'artefact à télécharger
          path: app