name: RELEASE
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure signature
        run: |
          echo "${{secrets.KEY_PROPERTIES}}" > android/key.properties
          echo "${{secrets.RELEASE_KEYSTORE}}" > file.encoded
          base64 -d -i file.encoded > ./android/app/file.jks
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.11'
      - name: Build apk
        run: |
          flutter pub get
          dart format --set-exit-if-changed .
          flutter build apk --split-per-abi
      - name: Retrieve Release Version
        id: versionstep
        run: |
          VERSION=$(more pubspec.yaml | grep version: | cut -d ' ' -f2)
          echo "::set-output name=VERSION::$VERSION"
      - name: Upload the APK onto Github
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/flutter-apk/*.apk'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.versionstep.outputs.VERSION }}